//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BionicCode.BionicNuGetDeploy.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BionicCode.BionicNuGetDeploy.Main.Properties.SettingsResources", typeof(SettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assemblyPath.
        /// </summary>
        internal static string AssemblyFilePath {
            get {
                return ResourceManager.GetString("AssemblyFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to includeSymbols.
        /// </summary>
        internal static string IsIncludingDebugSymbols {
            get {
                return ResourceManager.GetString("IsIncludingDebugSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to includeReferencedProjects.
        /// </summary>
        internal static string IsIncludingReferencedProjects {
            get {
                return ResourceManager.GetString("IsIncludingReferencedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastRecentFille.
        /// </summary>
        internal static string LastRecentUsedFile {
            get {
                return ResourceManager.GetString("LastRecentUsedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mruCount.
        /// </summary>
        internal static string MaxRecentlyUsedCount {
            get {
                return ResourceManager.GetString("MaxRecentlyUsedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mru.
        /// </summary>
        internal static string MostRecentlyUsed {
            get {
                return ResourceManager.GetString("MostRecentlyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        internal static string MostRecentlyUsedStringSeparator {
            get {
                return ResourceManager.GetString("MostRecentlyUsedStringSeparator", resourceCulture);
            }
        }
    }
}
